### ISSUE TITLE
Path of executable not taken into account

### ISSUE THREAD

**Issue by tainmar** [higoka/php-cs-fixer#1]
Hi,
When specifying the path of the `php-cs-fxer`, it does not take into account and sends the following error in the Output :

`Error: Command failed: /usr/local/bin/php-cs-fixer`

When I have specified another path

**Comment by higoka** [comment]
You may have to reload vscode after you changed any of the configuration.

**Comment by higoka** [comment]
im going to close this because its not an issue, just reload vscode and you should be fine. 
feel free to reopen if you need.

**Comment by dimaslanjaka** [comment]
not working anymore on windows
