### ISSUE TITLE
command 'php-cs-fixer.fix' not found

### ISSUE THREAD

**Issue by Flynsarmy** [higoka/php-cs-fixer#2]
Tried to run and got the error:

> Error: command 'php-cs-fixer.fix' not found
>     at u._tryExecuteCommand (workbench.desktop.main.js:sourcemap:3331)
>     at workbench.desktop.main.js:sourcemap:3331
>     at processTicksAndRejections (internal/process/task_queues.js:89)
>     at async t (workbench.desktop.main.js:sourcemap:4333)
> onDidNotificationChange | @ | notificationsAlerts.ts:38
> 

I had already reloaded/restarted VSC. The command executeable was set to the correct filepath.

**Comment by higoka** [comment]
What is your VS Code version?

**Comment by Flynsarmy** [comment]
1.42.0. Latest as of time of writing.

**Comment by higoka** [comment]
Your right, i got the same issue. In the developer console i got the error "```Activating extension 'higoka.php-cs-fixer' failed: Cannot read property 'document' of undefined.```". Im looking into it now.

**Comment by higoka** [comment]
It should be fixed now. Please let me know if it works.

**Comment by higoka** [comment]
I assume this has been resolved if not feel free to create another issue.
