### ISSUE TITLE
Cannot create intersection with not-fully defined Finder in configuration file.  

### ISSUE THREAD

**Issue by Flynsarmy** [higoka/php-cs-fixer#3]
When running the command I get:

> ERR Command failed: /path/to/php-cs-fixer fix /path/to/file.php --using-cache=no --path-mode=intersection
> Loaded config default.
> 
> In ConfigurationResolver.php line 844:
>                                                                                
>   Cannot create intersection with not-fully defined Finder in configuration f  
>   ile.                                                                         
>                                                                                
> 
> fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
> 
> : Error: Command failed: /path/to/php-cs-fixer fix /path/to/file.php --using-cache=no --path-mode=intersection
> Loaded config default.
> 
> In ConfigurationResolver.php line 844:
>                                                                                
>   Cannot create intersection with not-fully defined Finder in configuration f  
>   ile.                                                                         
>                                                                                
> 
> fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
> 
> 
> 	at ChildProcess.exithandler (child_process.js:303:12)
> 	at ChildProcess.emit (events.js:200:13)
> 	at maybeClose (internal/child_process.js:1021:16)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by higoka** [comment]
You need to define a config file. If you don't use one, set the path mode to "override"

**Comment by Flynsarmy** [comment]
Would it be possible to improve the error message when this is the case? ATM we just see:
![Screen Shot 2020-02-24 at 11 06 05 am](https://user-images.githubusercontent.com/334808/75123708-b6ad2c00-56f5-11ea-9b9b-2e67c20c26bc.png)

**Comment by higoka** [comment]
Yes of course. Do you have any suggestions?

**Comment by Flynsarmy** [comment]
> PHP-CS_Fixer: Path mode "intersection" requires a config file be set. Please set one or change path mode to "override".

Maybe something like this?

**Comment by Flynsarmy** [comment]
I changed path mode to intersection and still got the same error:

> /path/to/file.php --using-cache=no --path-mode=intersection
> Loaded config default.
> 
> In ConfigurationResolver.php line 844:
>                                                                                
>   Cannot create intersection with not-fully defined Finder in configuration f  
>   ile.                                                                         
>                                                                                
> 
> fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
> 
> : Error: Command failed: /path/to/php-cs-fixer fix /path/to/file.php --using-cache=no --path-mode=intersection
> Loaded config default.
> 
> In ConfigurationResolver.php line 844:
>                                                                                
>   Cannot create intersection with not-fully defined Finder in configuration f  
>   ile.                                                                         
>                                                                                
> 
> fix [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--dry-run] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--diff-format DIFF-FORMAT] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--] [<path>...]
> 
> 
> 	at ChildProcess.exithandler (child_process.js:303:12)
> 	at ChildProcess.emit (events.js:200:13)
> 	at maybeClose (internal/child_process.js:1021:16)
> 	at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)

**Comment by higoka** [comment]
This is much better. You can make a pull request if you want else i'm going to implement it in the next few days, kinda busy right now.

Thanks for your feedback and suggestion!

**Comment by higoka** [comment]
It has been implemented. See here: https://github.com/higoka/php-cs-fixer/commit/017835514f2eb0297ab211416147a37672a2c510

Thanks again for your suggestion!
